## A basic GitHub Actions workflow for your Quarkus application.

name: CI build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      # this will produce a local image called: lgao/helloworld:1.0.0-SNAPSHOT
      - name: Build Native Docker Image
        run: ./mvnw clean install -Pnative  -Dquarkus.native.container-build=true

      - name: Login to the registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Push the Native Docker Image to GitHub registry
        run: |
          MVN_VERSION="$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
          BUILT_IMG=${{ github.repository_owner }}/${{ github.repository_name }}:$MVN_VERSION
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:latest
          docker tag $BUILT_IMG $IMAGE_ID
          docker push $IMAGE_ID

